const timeDelay = 15000; // Thời gian chờ sau khi phát tiếng chuông thì sẽ phát nhạc (15000ms = 15s)
//Nếu type = 'ra_choi' thì sau khi playSound timeDelay giây thì hãy phát songNumber bài nhạc bất kỳ trong listMusic (không trùng với bài hát đã phát trong lần phát này)
                
const songNumRegular = 3; // Số lượng bài nhạc nhiều nhất sẽ phát liên tiếp với trường hợp type != 'ra_nghi'
const songNumber = 7; // Số lượng bài nhạc nhiều nhất sẽ phát liên tiếp với trường hợp type = 'ra_choi' - 
const songNumberPlaymusic = 15; // Số lượng bài nhạc nhiều nhất sẽ phát liên tiếp với trường hợp type = 'phat_nhac'  
// Nếu set = 0 thì sẽ không phát nhạc khi type = 'ra_choi' chỉ phát tiếng chuông
// Nếu set = 1000 thì sẽ phát liên tục cho đến khi giờ vào lớp hoặc hết các bài trong danh sách.

// Tên đăng nhập và mật khẩu
const validUsername = 'admin';
const validPassword = 'hth123';

//Mật khẩu khi khóa màn hình
const lockScreenPassword = 'hth123';

//Nếu thêm bài hát mới thì hãy thêm vào danh sách này
const listMusic = [
    "01Vui Đến Trường - Nhóm Hoa Tay - Nhạc Thiếu Nhi Sôi Động Remix.mp3",
    "02Mai truong noi hoc bao dieu hay.mp3",
    "03NHỚ ƠN THẦY CÔ - Mắt Ngọc - Zumba - Bài nhảy 20-11.mp3",
    "04Bụi Phấn - BÉ MẠNH TUẤN - Nhạc Thiếu Nhi _ Khi Thầy Viết Bảng - Tây Nguyên Phim Entertainment.mp3",
    "05Lời Thầy Cô - Như Hảo.mp3",
    "06Mái trường mến yêu - Sáng tác- Lê Quốc Thắng - Biểu diễn- Nhóm Cát Trắng.mp3",
    "07Ngươi Thây năm xưa.mp3",
    "08Bay lên nhé ước mơ học trò - Miu Lê ( Bản cắt ).mp3",
    "09Sống Như Những Đóa Hoa - Bé Mỹ AnhLyrics.mp3",
    "10Nụ Cười 18 20 - Doãn Hiếu (Official) - Hãy hết mình trên con đường ta chọn, hẹn gặp khi thành công'.mp3",
    "11Tháng Năm Học Trò Remix - MINH VY - Nhạc Thiếu Nhi NHẢY SÔI ĐỘNG, 4K.mp3",
    "12Bài Ca Tôm Cá - Yong Anhh ft. Bé Nguyễn Minh Chiến - OST Anh Thầy Ngôi Sao.mp3",
    "13CÂY ĐA QUÁN DỐC - Kiều Minh Tâm & CLB Sophia I BM Kids TV.mp3",
    "14Lời Ru Của Cô - Phương Khanh Ft. Bảo Ngọc - Thanh Xuân (Official).mp3",
    "15 Liên khúcNhững bài hát hay nhất về thầy cô giáo , trường lớp -Tặng thầy cô nhân ngày nhà giáo Việt Nam 20-11.mp3",
    "16THƯƠNG LẮM THẦY CÔ ƠI ! ( REMIX EDM ) - TẶNG CÁC THẦY CÔ GIÁO NHÂN NGÀY NHÀ GIÁO VIỆT NAM 20-11.mp3",
    "17NHỮNG BÀI HÁT HAY NHẤT TRONG NGÀY KHAI GIẢNG NĂM HỌC MỚI (2024 - 2025) #list #khaigiang #nhachay.mp3",
    "18Mong Ước Kỉ Niệm Xưa - Tam Ca 3A -- Video Lyric HD.mp3",
    "19CÔ GIÁO EM  Bé Ellie KHÁNH NGỌC [MV Official]  Nhạc Thiếu Nhi Cho Bé Hay Nhất 2022.mp3",
    "20Thương Lắm Thầy Cô Ơi! - Be Phan Hiếu Kiên.mp3"

  ]

// Ví dụ chỉnh sửa lịch
// {   id: 1,                           --> id không được trùng lặp
//     name: 'Giờ vào học-sáng',        --> Tên lịch
//     type: 'ra_nghi',                 --> Loại lịch: ra_nghi (phát ít bài hát), ra_choi (phát nhiều bài hát)
//     time: '07:00',                   --> Thời gian sẽ phát
//     sound: 'ring vao.mp3',           --> Âm thanh sẽ phát báo hiệu khi đến thời gian
// }, 
const scheduleTemplateData = [
    {
        name: 'Lịch thường ngày(chuông)',
        listTime: [
            {   id: 25,
                name: 'Thời gian phát nhạc-sáng',
                time: '06:45',
                type: 'phat_nhac',
                sound: 'none.mp3',
            },  
            {   id: 1,
                name: 'Giờ vào học-sáng',
                time: '07:00',
                type: 'ra_choi',
                sound: 'ring vao hoc.mp3',
            },              
            {   id: 2,  
                name: 'Vào tiết-1 (vào)',
                time: '07:15',
                sound: 'ring vao.mp3',
            },             
            {   id: 3,   
                name: 'Hết tiết-1 (ra)',
                type: 'ra_nghi',
                time: '08:00',
                sound: 'ring ra.mp3',
            },             
            {   id: 4,   
                name: 'Vào tiết-2 (vào)',
                time: '08:05',
                sound: 'ring vao.mp3',
            },    
            {   id: 6,      
                type: 'ra_choi',
                name: 'Ra chơi sáng',
                time: '08:50',
                sound: 'ring ra.mp3',
            },    
            {   id: 7,      
                name: 'Vào tiết-3 (vào)',
                time: '09:05',
                sound: 'ring vao.mp3',
            },             
            {   id: 8,      
                name: 'Hết tiết-3 (ra)',
                type: 'ra_nghi',
                time: '09:50',
                sound: 'ring ra.mp3',
            },  
            {   id: 9,      
                name: 'Vào tiết-4 (vào)',
                time: '09:55',
                sound: 'ring vao.mp3',
            },             
            {   id: 10,      
                name: 'Hết tiết-4 (ra)',
                type: 'ra_nghi',
                time: '10:40',
                sound: 'ring ra.mp3',
            }, 
            {   id: 11,      
                name: 'Vào tiết-5 (vào)',
                time: '10:45',
                sound: 'ring vao.mp3',
            },              
            {   id: 12,
                name: 'Giờ tan học-sáng',
                time: '11:30',
                sound: 'ring het gio.mp3',
            },
            {   id: 26,
                name: 'Thời gian phát nhạc-chiều',
                time: '12:15',
                type: 'phat_nhac',
                sound: 'none.mp3',
            },
            {   id: 13,
                name: 'Giờ vào học-chiều',
                type: 'ra_choi',
                time: '12:30',
                sound: 'ring vao hoc.mp3',  
            },
            {   id: 14,
                name: 'Vào tiết - 1 (vào)',
                time: '12:45',
                sound: 'ring vao.mp3',
            },             
            {   id: 15,   
                name: 'Hết tiết - 1 (ra)',
                type: 'ra_nghi',
                time: '13:30',
                sound: 'ring ra.mp3',
            },
            {   id: 16,
                name: 'Vào tiết - 2 (vào)',
                time: '13:35',
                sound: 'ring vao.mp3',
            },             
            {   id: 17,   
                name: 'Hết tiết - 2 (ra)',
                type: 'ra_nghi',
                time: '14:20',
                sound: 'ring ra.mp3',
            },
            {   id: 18,
                name: 'Vào tiết - 3 (vào)',
                time: '14:25',
                sound: 'ring vao.mp3',
            },
            {   id: 20,   
                name: 'Ra chơi chiều',
                type: 'ra_choi',
                time: '15:10',
                sound: 'ring ra.mp3',
            },
            {   id: 21,   
                name: 'Vào tiết - 4 (vào)',
                time: '15:25',
                sound: 'ring vao.mp3',
            },             
            {   id: 22,   
                name: 'Hết tiết - 4 (ra)',
                type: 'ra_nghi',
                time: '16:10',
                sound: 'ring ra.mp3',
            },
            {   id: 23,   
                name: 'Vào tiết - 5 (vào)',
                time: '16:15',
                sound: 'ring vao.mp3',
            },
            {   id: 24,   
                name: 'Giờ tan trường-chiều',
                time: '17:00',
                sound: 'ring het gio.mp3',
            }
        ]
    }, {
        name: 'Lịch thường ngày(trống)',
        listTime: [
            {   id: 25,
                name: 'Thời gian phát nhạc-sáng',
                time: '06:45',
                type: 'phat_nhac',
                sound: 'none.mp3',
            },{   id: 1,
                name: 'Giờ vào học-sáng',
                time: '07:00',
                type: 'ra_choi',
                sound: 'Vaohoc.mp3',
            },              
            {   id: 2,  
                name: 'Vào tiết-1 (vào)',
                time: '07:15',
                sound: 'Vao3.mp3',
            },             
            {   id: 3,   
                name: 'Hết tiết-1 (ra)',
                type: 'ra_nghi',
                time: '08:00',
                sound: 'Ra1.mp3',
            },             
            {   id: 4,   
                name: 'Vào tiết-2 (vào)',
                time: '08:05',
                sound: 'Vao3.mp3',
            },    
            {   id: 6,      
                type: 'ra_choi',
                name: 'Ra chơi sáng',
                time: '08:50',
                sound: 'Ra1.mp3',
            },    
            {   id: 7,      
                name: 'Vào tiết-3 (vào)',
                time: '09:05',
                sound: 'Vao3.mp3',
            },             
            {   id: 8,      
                name: 'Hết tiết-3 (ra)',
                type: 'ra_nghi',
                time: '09:50',
                sound: 'Ra1.mp3',
            },  
            {   id: 9,      
                name: 'Vào tiết-4 (vào)',
                time: '09:55',
                sound: 'Vao3.mp3',
            },             
            {   id: 10,      
                name: 'Hết tiết-4 (ra)',
                type: 'ra_nghi',
                time: '10:40',
                sound: 'Ra1.mp3',
            }, 
            {   id: 11,      
                name: 'Vào tiết-5 (vào)',
                time: '10:45',
                sound: 'Vao3.mp3',
            },              
            {   id: 12,
                name: 'Giờ tan học-sáng',
                time: '11:30',
                sound: 'Tantruong.mp3',
            },
            {   id: 26,
                name: 'Thời gian phát nhạc-chiều',
                time: '12:15',
                type: 'phat_nhac',
                sound: 'none.mp3',
            },
            {   id: 13,
                name: 'Giờ vào học-chiều',
                type: 'ra_choi',
                time: '12:30',
                sound: 'Vaohoc.mp3',  
            },
            {   id: 14,
                name: 'Vào tiết - 1 (vào)',
                time: '12:45',
                sound: 'Vao3.mp3',
            },             
            {   id: 15,   
                name: 'Hết tiết - 1 (ra)',
                type: 'ra_nghi',
                time: '13:30',
                sound: 'Ra1.mp3',
            },
            {   id: 16,
                name: 'Vào tiết - 2 (vào)',
                time: '13:35',
                sound: 'Vao3.mp3',
            },             
            {   id: 17,   
                name: 'Hết tiết - 2 (ra)',
                type: 'ra_nghi',
                time: '14:20',
                sound: 'Ra1.mp3',
            },
            {   id: 18,
                name: 'Vào tiết - 3 (vào)',
                time: '14:25',
                sound: 'Vao3.mp3',
            },
            {   id: 20,   
                name: 'Ra chơi chiều',
                type: 'ra_choi',
                time: '15:10',
                sound: 'Ra1.mp3',
            },
            {   id: 21,   
                name: 'Vào tiết - 4 (vào)',
                time: '15:25',
                sound: 'Vao3.mp3',
            },             
            {   id: 22,   
                name: 'Hết tiết - 4 (ra)',
                type: 'ra_nghi',
                time: '16:10',
                sound: 'Ra1.mp3',
            },
            {   id: 23,   
                name: 'Vào tiết - 5 (vào)',
                time: '16:15',
                sound: 'Vao3.mp3',
            },
            {   id: 24,   
                name: 'Giờ tan trường-chiều',
                time: '17:00',
                sound: 'Tantruong.mp3',
            }
        ]
    }
];

// Giới hạn số lượng bài hát
const song1 = 1;
const song2 = 2;
const song3 = 3;

//Các tuy chọn âm thanh khi tạo thêm lịch
const options = [  
    {value: 'ring.mp3', text: 'Chuông reo'},
    {value: 'ring vao.mp3', text: 'Chuông vào lớp'},
    {value: 'ring ra.mp3', text: 'Chuông giờ ra'},
    {value: 'ring het gio.mp3', text: 'Chuông giờ tan học'},  
    {value: 'ring vao hoc.mp3', text: 'Chuông giờ vào học'},
    {value: 'Vao3.mp3', text: 'Trống vào lớp'},
    {value: 'Ra1.mp3', text: 'Trống giờ ra'},
    {value: 'Tantruong.mp3', text: ' Trống giờ tan học'},  
    {value: 'Vaohoc.mp3', text: 'Trống giờ vào học'},
    {value: 'none.mp3', text: 'none'},
];  